/**:
  ros__parameters:

    # frame id
    frame_id_slam_frame: "slam"


    # input
    topic_sub_odom:  "fastlio2/odometry"               # NOTE: SLAM to sensor frame
    topic_sub_cloud: "fastlio2/cloud/registered_body"  # NOTE:      in sensor frame


    # keyframe
    keyframe_gap_meter:  1.5
    keyframe_gap_deg:   15.0


    # voxel grid filter
    leaf_size_keyframe: 0.3
    leaf_size_icp:      0.3


    # visualization
    # NOTE: scpgo/cloud/keyframe (SLAM frame)
    enable_pub_cloud_keyframe: true

    # NOTE: scpgo/graph
    enable_pub_graph: true
    nodes_scale:      0.3
    nodes_alpha:      0.9
    edges_scale:      0.1
    edges_alpha:      0.9
    loops_pass_scale: 0.1
    loops_pass_alpha: 0.9
    loops_fail_scale: 0.1
    loops_fail_alpha: 0.9


    # debug
    print_thread_pose_graph: false  # FIX: remove ?
