/**:
  ros__parameters:

    # frame id
    frame_id_slam_frame: "slam"


    # input
    topic_sub_odom:  "fastlio2/odometry"               # NOTE: SLAM to sensor frame
    topic_sub_cloud: "fastlio2/cloud/registered_body"  # NOTE:      in sensor frame


    # keyframe selection
    keyframe_gap_meter:  1.5
    keyframe_gap_deg:   30.0


    # voxel grid filter
    leaf_size_keyframe: 0.3
    leaf_size_icp:      0.3


    # loop candidate
    lc_max_radius_m:     3.0
    lc_min_time_diff_s: 10.0


    # ICP test
    icp_stack_size:  15
    icp_max_fitness:  0.3


    # visualization
    # NOTE: pgo/cloud/keyframe (SLAM frame)
    enable_pub_cloud_keyframe: true

    # NOTE: pgo/icp/source  (SLAM frame)
    # NOTE: pgo/icp/target  (SLAM frame)
    # NOTE: pgo/icp/aligned (SLAM frame)
    enable_pub_icp: true

    # NOTE: scpgo/graph
    enable_pub_graph: true
    nodes_scale:      0.15
    nodes_alpha:      0.9
    edges_scale:      0.05
    edges_alpha:      0.9
    loops_pass_scale: 0.05
    loops_pass_alpha: 0.9
    loops_fail_scale: 0.05
    loops_fail_alpha: 0.9
